### ISSUE TITLE
Enabling inclusion of LaTeX packages in the YAML header

### ISSUE THREAD

**Issue by ArnaudKunzi** [CTU-Bern/CTUtemplate#22]
**Is your feature request related to a problem? Please describe.**
Some reports have very specific formatting needs that require the inclusion of LaTeX packages not included in the template. (Some of the more advanced users might also want to include a custom package)

**Describe the solution you'd like**  

![image](https://user-images.githubusercontent.com/22870774/124475103-a1dcb000-dda1-11eb-8582-94268be48a04.png)

or a way to parse:

![image](https://user-images.githubusercontent.com/22870774/124475666-4232d480-dda2-11eb-90cb-3707ded82cd2.png)

**Describe alternatives you've considered**
None come to mind

**Additional context**

**Comment by aghaynes** [comment]
#23 includes a way to copy the latex file to the directory and use that instead of the default one. 

use `CTUtemplate::use_ub_tex_template(folder/report.tex)` to copy the tex template to the folder.

In the header, output should then be 
``` 
output: 
  CTUtemplate::report_pdf:
    report_template: "report.tex"
```
