### ISSUE TITLE
Missing latex package dependency for pdflscape?

### ISSUE THREAD

**Issue by ArnaudKunzi** [CTU-Bern/CTUtemplate#37]
Note that I had to add 
```
header-includes:
  - \usepackage{pdflscape}
```
to the header to compile the report template. Is it missing by default?

**To Reproduce**
run CTUtemplate::use_report_template() and try to knit the file

Note that I am using MikteX and not tinytex. not sure if that has any bearing in the matter.

**Comment by aghaynes** [comment]
so that I dont forget that we discussed it... try `landscape: true` the same way as the `toc: true` etc is done
